### ISSUE TITLE
Vercel build failing

### ISSUE THREAD

**Issue by ractoon** [MasteringNuxt/NuxtBnB#14]
When trying to deploy the application to Vercel I'm receiving the following errors and it does not complete:

```
21:38:18.251
[log] Running with @nuxt/vercel-builder version 0.21.3
21:38:18.251
[log]  ----------------- Prepare build ----------------- 
21:38:18.251
[log] Downloading files...
21:38:18.251
[log] Working directory: /vercel/path0
21:38:18.256
[log] Using yarn
21:38:18.257
[info] Prepare build took: 6.221263 ms
21:38:18.257
[log]  ----------------- Install devDependencies ----------------- 
21:38:18.566
yarn install v1.22.11
21:38:18.583
warning package.json: No license field
21:38:18.654
warning nuxt-bnb: No license field
21:38:18.657
[1/5] Resolving packages...
21:38:19.293
[2/5] Fetching packages...
21:38:43.532
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
21:38:43.533
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
21:38:43.545
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
21:38:43.545
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
21:38:43.553
[3/5] Linking dependencies...
21:38:43.559
warning "@nuxtjs/cloudinary > cloudinary-core@2.11.4" has unmet peer dependency "lodash@>=4.0".
21:38:43.559
warning " > cloudinary-vue@1.2.3" has unmet peer dependency "vue@^2.0.0".
21:38:43.559
warning "nuxt > @nuxt/components@2.2.1" has unmet peer dependency "consola@*".
21:38:43.570
warning " > v-calendar@2.3.2" has unmet peer dependency "@popperjs/core@^2.4.0".
21:38:43.570
warning " > v-calendar@2.3.2" has unmet peer dependency "vue@^2.5.18".
21:38:43.572
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
21:38:43.572
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
21:38:43.574
warning " > sass-loader@10.2.0" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
21:38:55.096
[4/5] Building fresh packages...
21:38:58.830
warning Error running install script for optional dependency: "/vercel/path0/node_modules/sharp: Command failed.
21:38:58.830
Exit code: 1
21:38:58.830
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
21:38:58.831
Arguments: 
21:38:58.831
Directory: /vercel/path0/node_modules/sharp
21:38:58.831
Output:
21:38:58.831
sharp: Using cached /vercel/.npm/_libvips/libvips-8.11.3-linux-x64.tar.br
21:38:58.831
/bin/sh: prebuild-install: command not found
21:38:58.831
gyp info it worked if it ends with ok
21:38:58.831
gyp info using node-gyp@5.1.0
21:38:58.831
gyp info using node@14.17.6 | linux | x64
21:38:58.831
gyp info find Python using Python version 2.7.18 found at \"/usr/bin/python\"
21:38:58.831
gyp http GET https://nodejs.org/download/release/v14.17.6/node-v14.17.6-headers.tar.gz
21:38:58.831
gyp http 200 https://nodejs.org/download/release/v14.17.6/node-v14.17.6-headers.tar.gz
21:38:58.831
gyp http GET https://nodejs.org/download/release/v14.17.6/SHASUMS256.txt
21:38:58.831
gyp http 200 https://nodejs.org/download/release/v14.17.6/SHASUMS256.txt
21:38:58.832
gyp info spawn /usr/bin/python
21:38:58.832
gyp info spawn args [
21:38:58.832
gyp info spawn args   '/node14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
21:38:58.832
gyp info spawn args   'binding.gyp',
21:38:58.832
gyp info spawn args   '-f',
21:38:58.832
gyp info spawn args   'make',
21:38:58.832
gyp info spawn args   '-I',
21:38:58.832
gyp info spawn args   '/vercel/path0/node_modules_dev/sharp/build/config.gypi',
21:38:58.832
gyp info spawn args   '-I',
21:38:58.832
gyp info spawn args   '/node14/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
21:38:58.832
gyp info spawn args   '-I',
21:38:58.833
gyp info spawn args   '/vercel/.cache/node-gyp/14.17.6/include/node/common.gypi',
21:38:58.833
gyp info spawn args   '-Dlibrary=shared_library',
21:38:58.833
gyp info spawn args   '-Dvisibility=default',
21:38:58.833
gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/14.17.6',
21:38:58.833
gyp info spawn args   '-Dnode_gyp_dir=/node14/lib/node_modules/npm/node_modules/node-gyp',
21:38:58.833
gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
21:38:58.833
gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules_dev/sharp',
21:38:58.833
gyp info spawn args   '-Dnode_engine=v8',
21:38:58.833
gyp info spawn args   '--depth=.',
21:38:58.834
gyp info spawn args   '--no-parallel',
21:38:58.834
gyp info spawn args   '--generator-output',
21:38:58.834
gyp info spawn args   'build',
21:38:58.834
gyp info spawn args   '-Goutput_dir=.'
21:38:58.834
gyp info spawn args ]
21:38:58.834
gyp info spawn make
21:38:58.834
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
21:38:58.834
make: Entering directory `/vercel/path0/node_modules_dev/sharp/build'
21:38:58.834
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
21:38:58.834
  AR(target) Release/obj.target/../node-addon-api/nothing.a
21:38:58.835
  COPY Release/nothing.a
21:38:58.835
  TOUCH Release/obj.target/libvips-cpp.stamp
21:38:58.835
  CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
21:38:58.835
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
21:38:58.835
 #include <vips/vips8>
21:38:58.835
          ^~~~~~~~~~~~
21:38:58.835
compilation terminated.
21:38:58.836
make: *** [Release/obj.target/sharp-linux-x64/src/common.o] Error 1
21:38:58.836
make: Leaving directory `/vercel/path0/node_modules_dev/sharp/build'
21:38:58.836
gyp ERR! build error 
21:38:58.836
gyp ERR! stack Error: `make` failed with exit code: 2
21:38:58.836
gyp ERR! stack     at ChildProcess.onExit (/node14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
21:38:58.836
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
21:38:58.836
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
21:38:58.836
gyp ERR! System Linux 4.14.243-185.433.amzn2.x86_64
21:38:58.836
gyp ERR! command \"/node14/bin/node\" \"/node14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
21:38:58.837
gyp ERR! cwd /vercel/path0/node_modules_dev/sharp
21:38:58.837
gyp ERR! node -v v14.17.6
21:38:58.837
gyp ERR! node-gyp -v v5.1.0
21:38:58.837
gyp ERR! not ok"
21:38:58.837
info This module is OPTIONAL, you can safely ignore this error
21:38:59.168
[5/5] Cleaning modules...
21:39:03.060
Done in 44.50s.
21:39:03.087
[info] Install devDependencies took: 44829.343461 ms
21:39:03.087
[log]  ----------------- Nuxt build ----------------- 
21:39:03.366
[log] Running nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0
21:39:03.870
[error] [@nuxt/image] `ipx` is an optional dependency for local image optimization and is not properly installed. Please try `npm install` or `yarn install` again.
21:39:03.871
[fatal] Error: Cannot find module 'sharp'
21:39:03.871
Require stack:
21:39:03.871
- /vercel/path0/node_modules_dev/ipx/dist/index.cjs
21:39:03.871
- /vercel/path0/node_modules_dev/@nuxt/image/dist/module.js
21:39:03.871
- /vercel/path0/node_modules_dev/@nuxt/core/dist/core.js
21:39:03.871
  Require stack:
21:39:03.871
  - node_modules_dev/ipx/dist/index.cjs
21:39:03.871
  - node_modules_dev/@nuxt/image/dist/module.js
21:39:03.871
  - node_modules_dev/@nuxt/core/dist/core.js
21:39:03.871
  at node_modules_dev/@nuxt/image/dist/module.js:132:13
21:39:03.871
  at async Object.ipxSetup [as setup] (node_modules_dev/@nuxt/image/dist/module.js:130:48)
21:39:03.871
  at async ModuleContainer.imageModule2 (node_modules_dev/@nuxt/image/dist/module.js:271:7)
21:39:03.871
  at async ModuleContainer.addModule (node_modules_dev/@nuxt/core/dist/core.js:239:20)
21:39:03.872
  at async ModuleContainer.ready (node_modules_dev/@nuxt/core/dist/core.js:51:7)
21:39:03.872
  at async Nuxt._init (node_modules_dev/@nuxt/core/dist/core.js:478:5)
21:39:03.879
21:39:03.879
   ╭─────────────────────────────────────────────────────────────────╮
21:39:03.879
   │                                                                 │
21:39:03.879
   │   ✖ Nuxt Fatal Error                                            │
21:39:03.879
   │                                                                 │
21:39:03.880
   │   Error: Error: Cannot find module 'sharp'                      │
21:39:03.880
   │   Require stack:                                                │
21:39:03.880
   │   - /vercel/path0/node_modules_dev/ipx/dist/index.cjs           │
21:39:03.880
   │   - /vercel/path0/node_modules_dev/@nuxt/image/dist/module.js   │
21:39:03.880
   │   - /vercel/path0/node_modules_dev/@nuxt/core/dist/core.js      │
21:39:03.880
   │                                                                 │
21:39:03.880
   ╰─────────────────────────────────────────────────────────────────╯
21:39:03.880
21:39:03.892
Error: Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0
21:39:03.892
    at makeError (/vercel/cea6d456332c12ca/.build-utils/.builder/node_modules/execa/lib/error.js:60:11)
21:39:03.892
    at handlePromise (/vercel/cea6d456332c12ca/.build-utils/.builder/node_modules/execa/index.js:118:26)
21:39:03.892
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:39:03.892
    at Object.build (/vercel/cea6d456332c12ca/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:347:3)
21:39:03.892
    at buildStep (/var/task/webpack:/@vercel/api/scripts/build-container/src/utils/purpose-build.ts:164:1) {
21:39:03.892
  shortMessage: 'Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0',
21:39:03.892
  command: 'npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0',
21:39:03.893
  escapedCommand: 'npx nuxt build --standalone --no-lock "--config-file \\"nuxt.config.js\\"" "/vercel/path0"',
21:39:03.893
  exitCode: 1,
21:39:03.893
  signal: undefined,
21:39:03.893
  signalDescription: undefined,
21:39:03.893
  stdout: undefined,
21:39:03.893
  stderr: undefined,
21:39:03.893
  failed: true,
21:39:03.893
  timedOut: false,
21:39:03.893
  isCanceled: false,
21:39:03.894
  killed: false
21:39:03.894
}
```

Here is my `package.json` file:

```
{
  "name": "nuxt-bnb",
  "dependencies": {
    "@nuxtjs/cloudinary": "^1.0.3",
    "body-parser": "^1.19.0",
    "cloudinary-vue": "^1.2.3",
    "cookie": "^0.4.1",
    "google-auth-library": "^7.6.1",
    "js-cookie": "^3.0.0",
    "nuxt": "^2.15.7",
    "stripe": "^8.174.0",
    "uuid": "^8.3.2",
    "v-calendar": "^2.3.2"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
  },
  "devDependencies": {
    "@nuxt/image": "^0.6.0",
    "@nuxtjs/tailwindcss": "^4.2.1",
    "sass": "^1.37.5",
    "sass-loader": "^10.1.1"
  }
}
```

And `vercel.json` file:

```
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/vercel-builder",
      "config":{
        "serverFiles":["modules/**", "utils/**"]
      }
    }
  ]
}
```

Am I missing something on my end to get this to build successfully? Thanks!

**Comment by alexdohmen** [comment]
Maybe it is related to this issue?
https://github.com/nuxt/image/issues/344

**Comment by ractoon** [comment]
> Maybe it is related to this issue?
> [nuxt/image#344](https://github.com/nuxt/image/issues/344)

That was it, thank you! My `package.json` now looks like this and builds successfully:

```
{
  "name": "nuxt-bnb",
  "dependencies": {
    "@nuxtjs/cloudinary": "^1.0.3",
    "body-parser": "^1.19.0",
    "cloudinary-vue": "^1.2.3",
    "cookie": "^0.4.1",
    "google-auth-library": "^7.6.1",
    "js-cookie": "^3.0.0",
    "nuxt": "^2.15.7",
    "stripe": "^8.174.0",
    "uuid": "^8.3.2",
    "v-calendar": "^2.3.2"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
  },
  "devDependencies": {
    "@nuxt/image": "^0.6.0",
    "@nuxtjs/tailwindcss": "^4.2.1",
    "sass": "^1.37.5",
    "sass-loader": "^10.1.1"
  },
  "resolutions": {
    "sharp": "0.27.0"
  }
}
```

**Comment by baydiwo** [comment]
hi @ractoon can you show me your nuxt config ? I also stuck with this

**Comment by ractoon** [comment]
Hi @baydiwo, sure thing it is: https://github.com/ractoon/nuxt-bnb/blob/master/nuxt.config.js

However, I converted all the keys to ENV variables so if copying that file exactly you'd need to copy this file: https://github.com/ractoon/nuxt-bnb/blob/master/.env.example, rename it to `.env` and fill in your values.
